import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#4e1a08ff',
  secondary: '#d77514ff',
  background: '#f5f5f5',
  white: '#ffffff',
  text: '#a10101ff',
  textLight: '#000000ff',
  border: '#ddd',
  error: '#f44336',
  success: '#4CAF50',
  warning: '#FF9800',
  favorite: '#e91e63',
  gold: '#FFD700'
};

export const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    width: '100%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: colors.textLight,
    textAlign: 'center',
    marginBottom: 24,
  },
  input: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 16,
  },
  button: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  buttonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  link: {
    color: colors.primary,
    fontWeight: 'bold',
  },
  linkText: {
    textAlign: 'center',
    marginTop: 20,
    color: colors.textLight,
  },
  header: {
    backgroundColor: colors.primary,
    padding: 16,
    paddingTop: 50,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.white,
    textAlign: 'center',
    marginBottom: 16,
  },
  searchBox: {
    flexDirection: 'row',
    marginTop: 12,
  },
  searchInput: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginRight: 8,
  },
  searchButton: {
    backgroundColor: colors.secondary,
    borderRadius: 8,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  movieCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    margin: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  moviePoster: {
    width: '100%',
    height: 400,
    borderRadius: 8,
    marginBottom: 12,
  },
  movieTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 8,
  },
  movieRating: {
    fontSize: 16,
    color: colors.textLight,
    marginBottom: 4,
  },
  movieStars: {
    fontSize: 18,
    color: colors.gold,
    marginBottom: 8,
  },
  movieGenres: {
    fontSize: 14,
    color: colors.textLight,
    marginBottom: 12,
  },
  moviePlot: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
    marginBottom: 12,
  },
  movieDirector: {
    fontSize: 14,
    color: colors.textLight,
    marginBottom: 16,
  },
  actionButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  favoriteButton: {
    backgroundColor: colors.favorite,
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  actionButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: 'bold',
  },
});
